version: '3.8'

services:
  open-computer-use-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - E2B_API_KEY=${E2B_API_KEY}
    volumes:
      - ./output:/app/output
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
